### ISSUE TITLE
Crash on server load

### ISSUE THREAD

**Issue by krofna** [krofna/Warrior-of-Dreamworld-r3#2]
```
std::ifstream CharactersFile("CharactersServer.conf");
std::ifstream LogFile("LogConfig.conf");
```

Where are those files :P ? As far as I know the Log is configured in same file as world, while I have no idea what CharacterServer.conf is.

**Comment by krofna** [comment]
Here is bt if you prefer:

`#0  0x0000003af3c35ba5 in raise () from /lib64/libc.so.6
#1  0x0000003af3c37358 in abort () from /lib64/libc.so.6
#2  0x0000003af7860e1d in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x0000003af785eeb6 in ?? () from /lib64/libstdc++.so.6
#4  0x0000003af785eee3 in std::terminate() () from /lib64/libstdc++.so.6
#5  0x0000003af785f10e in __cxa_throw () from /lib64/libstdc++.so.6
#6  0x000000000051b38c in Configurable::GetNextToken<unsigned char> (this=0x761120 <sLog>, Config=..., Data=@0x761328: 0 '\000')
    at /home/krofna/Development/Warrior-of-Dreamworld-r3/Shared/Configurable.hpp:38
#7  0x000000000051b1d1 in Log::LoadFromConfig (this=0x761120 <sLog>, Config=...)
    at /home/krofna/Development/Warrior-of-Dreamworld-r3/Shared/Log.cpp:31
#8  0x0000000000509b98 in Main::Load (this=0x764fb0, argc=1, argv=0x7fffffffe0a8)
    at /home/krofna/Development/Warrior-of-Dreamworld-r3/Server/World/Main.cpp:58
#9  0x000000000050a456 in main (argc=1, argv=0x7fffffffe0a8) at /home/krofna/Development/Warrior-of-Dreamworld-r3/Server/World/Main.cpp:126
`

**Comment by RaitoBezarius** [comment]
What is the content of your LogConfig.conf ?
