### ISSUE TITLE
Fix GetNextToken

### ISSUE THREAD

**Issue by krofna** [krofna/Warrior-of-Dreamworld-r3#3]
``#0 0x0000003af3c35ba5 in raise () from /lib64/libc.so.6
#1 0x0000003af3c37358 in abort () from /lib64/libc.so.6
#2 0x0000003af7860e1d in gnu_cxx::verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3 0x0000003af785eeb6 in ?? () from /lib64/libstdc++.so.6
#4 0x0000003af785eee3 in std::terminate() () from /lib64/libstdc++.so.6
#5 0x0000003af785f10e in __cxa_throw () from /lib64/libstdc++.so.6
#6 0x00000000004ebf08 in boost::throw_exceptionboost::bad_lexical_cast (e=...) at /usr/include/boost/throw_exception.hpp:67
#7 0x000000000051b6ad in boost::detail::lexical_cast_do_cast::lexical_cast_impl (arg="0 2")

at /usr/include/boost/lexical_cast.hpp:1975
#8 0x000000000051b603 in boost::lexical_cast (arg="0 2") at /usr/include/boost/lexical_cast.hpp:2133
#9 0x000000000051b5e9 in ToType (String="0 2") at /home/krofna/Development/Warrior-of-Dreamworld-r3/Shared/Utility.hpp:56
#10 0x000000000051b53c in Configurable::GetNextToken (this=0x761120 , Config=..., Data=@0x761328: 0 '\000')

at /home/krofna/Development/Warrior-of-Dreamworld-r3/Shared/Configurable.hpp:46
#11 0x000000000051b265 in Log::LoadFromConfig (this=0x761120 , Config=...)

at /home/krofna/Development/Warrior-of-Dreamworld-r3/Shared/Log.cpp:31
#12 0x0000000000509c4f in Main::Load (this=0x764fb0, argc=1, argv=0x7fffffffe0a8)

at /home/krofna/Development/Warrior-of-Dreamworld-r3/Server/World/Main.cpp:57
#13 0x000000000050a4ea in main (argc=1, argv=0x7fffffffe0a8) at /home/krofna/Development/Warrior-of-Dreamworld-r3/Server/World/Main.cpp:125``

**Comment by RaitoBezarius** [comment]
Please, explain what GetNextToken should do exactly.
I've told you that he won't read something like : 
"0 2 3 4 5 6 7"

**Comment by krofna** [comment]
0 1
2 3

Should read:
0
1
2
3
(4 calls)

**Comment by RaitoBezarius** [comment]
'Kay.
